services:
  backend:
    build: ./fastApiApp
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build: ./reactFrontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: pgvector/pgvector:pg18
    ports:
      - "5433:5432" # First part -> 5433 when docker and 5432 when local
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: